networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:6.2.2
    hostname: kafka
    container_name: kafka
    ports:
        - "9092:9092"
        - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy  
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 60s

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - kafka-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./utils/init_scripts:/docker-entrypoint-initdb.d
      - ./utils/init_scripts/init_base.sql:/docker-entrypoint-initdb.d/init_base.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s
    networks:
      - kafka-network

  back:
    build:
      context: ./services/
      dockerfile: ./back/Dockerfile
    command: poetry run app -V
    container_name: back
    restart: unless-stopped
    volumes:
      - ./services/back/:/app/
      - ./utils/:/app/back/utils/
      - ./back_logs/:/app/logs/
    env_file:
      - ./.env
    ports:
      - 8004:8000
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - kafka-network

  orders:
    build:
      context: ./services/
      dockerfile: ./orders/Dockerfile
    command: poetry run app -V
    container_name: orders
    restart: unless-stopped
    volumes:
      - ./services/orders/:/app/
      - ./utils/:/app/orders/utils/
    env_file:
      - ./.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - kafka-network

  frontend-shell:
    build:
      context: ./frontend/frontend_shell
      dockerfile: Dockerfile
    container_name: frontend-shell
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - kafka-network
    depends_on:
      - mf-orders
      - mf-admin
      - back

  mf-orders:
    build:
      context: ./frontend/mf_orders
      dockerfile: Dockerfile
    container_name: mf-orders
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - kafka-network

  mf-admin:
    build:
      context: ./frontend/mf_admin
      dockerfile: Dockerfile
    container_name: mf-admin
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - kafka-network

  mf-cart:
    build:
      context: ./frontend/mf_cart
      dockerfile: Dockerfile
    container_name: mf-cart
    restart: unless-stopped
    ports:
      - "3003:80"
    networks:
      - kafka-network

volumes:
  postgres_data: